# Generated by Django 4.2.9 on 2024-03-06 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, upload_to='userimages/')),
                ('linkedin_password', models.CharField(max_length=100)),
                ('indeed_password', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=250)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
