# Generated by Django 4.2.9 on 2024-03-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alljobs_dicejob_indeedjob_ziprecruiterjob_scrapedjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicejob',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
