# Generated by Django 4.2.9 on 2024-03-14 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_alter_dicejob_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedjob',
            old_name='job_description',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='alljobs',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
