# Generated by Django 4.2.9 on 2024-03-14 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_rename_job_description_scrapedjob_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeedjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scrapedjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
