# Generated by Django 4.2.9 on 2024-03-14 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_alter_indeedjob_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicejob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobsearcherrors',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='naukrijob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ziprecruiterjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
